title: CloudOps with Satya
description: DevOps | Azure | AKS | Terraform | CI/CD
theme: minima
markdown: kramdown
minima:
  skin: auto

header_pages:
  - home.md
  - blog.md
  - projects.md
  - interview.md
  - contact.md




